### ISSUE TITLE
Why not just use EIP-2981?

### ISSUE THREAD

**Issue by sheeeev66** [manifoldxyz/royalty-registry-solidity#12]
EIP-2981 does the exact same thing. So in production, there is no real reason why to use this "royalty registry".
Why still create this? 
(honest question lol. Don't take this as me trying to insult you or something. Your work is amazing so keep it up)

**Comment by wwhchung** [comment]
Because this provides a way for non-compliant contracts (i.e. every single contract prior to EIP2981) to add on-chain royalties (plus adding support for existing on-chain royalty solutions mapped to a common interface, like Rarible), which is a major blocker for widespread adoption by the marketplaces.

You don't have to use this if your contract supports EIP2981, this is really an interface for marketplaces and those with contracts out there that existed prior to EIP2981 and only configured royalties on offchain systems like OpenSea.

**Comment by wwhchung** [comment]
It's all answered here:
https://royaltyregistry.xyz/lookup#faq
