### ISSUE TITLE
Opensea clarification

### ISSUE THREAD

**Issue by gigamesh** [manifoldxyz/royalty-registry-solidity#14]
Awesome project! We might make use of it at sound.xyz

I'm unable to find any mention of EIP-2981 or this project in Opensea's documentation.

Are they using EIP-2981 yet? If not, does anyone know when they will be?

**Comment by vrde** [comment]
@gigamesh this issue might be interesting for you https://github.com/ProjectOpenSea/seaport/issues/306

**Comment by wwhchung** [comment]
They are now ingesting eip2981 data.

**Comment by shoenseiwaso** [comment]
> They are now ingesting eip2981 data.

Great! Do you have any more context or links on details about this? All I could find was [this tweet](https://twitter.com/opensea/status/1600913315576049669).

Asking because in the past they have had inconsistent support for payouts to smart contracts, and one popular EIP-2981 pattern is to connect a multisig or 0xSplit to the EIP-2981 receiver address. Would be great if there is more OpenSea documentation on it.

**Comment by wwhchung** [comment]
You should follow along this PR which is being contributed to by OpenSea folks. 

https://github.com/manifoldxyz/royalty-registry-solidity/pull/35

Not sure when they’ll fully announce/document things.
