### ISSUE TITLE
Is it intentional that royalties can be overridden even when existing on chain royalties exist?

### ISSUE THREAD

**Issue by jdmwood** [manifoldxyz/royalty-registry-solidity#37]
It seems from the way the engine works, it will always use the override extension provided by `setRoyaltyLookupAddress` first before anything else.

So, even if the existing contract already has, say, ERC-2981, you can effectively always override it.

I can understand both sides of the argument: On the one hand, you could argue that a hard coded royalty in the original contract should win so that buyers understand what royalties are going to applied at a later date. On the other hand, you could argue that creators should be in control and even decide to change their mind at a later date.

I just wanted to check: was this intentional or just an accident? It would be useful to understand if this is a intentional decision and one that won't change in future versions of the registry.

Keep up the good work!

**Comment by wwhchung** [comment]
It’s intentional. The contract owner always has the ability to modify/override the royalty info. Even marketplaces like OpenSea/etc allow modification of royalties at any time. 

To note, even with eip2891, nothing prevents the royalties from being modified. You could write a smart contract where you have the ability to change it. So we didn’t really feel that this aspect was any more/less immutable. 

Finally, even if hardcoded, there are legitimate reasons for overriding royalty data post contract deployment (Eg changing recipient addresses due to a compromised wallet). 

The royalty engine is really a reference implementation that most marketplaces have chosen to adopt. However, the registry itself is the source of data. Anyone could write or integrate their own lookup engine that orders it the other way around.

**Comment by jdmwood** [comment]
Thanks, that makes complete sense and is a valuable insight into the intent of the registry.
